votes-api:
  configurations:
    datasource:
      host: localhost
      port: 27017
      database: votes-db
      username: votes
      password: votes
      authentication-database: admin
    thread:
      core: 2
      poolSize: 2
      queueCapacity: 100
    kafka:
      producer:
        bootstrapServerHost: localhost:9092
        topic: test
    redis:
      host: 127.0.0.1
      port: 6379