votes-api:
  configurations:
    datasource:
      host: ~
      port: 0
      database: ~
      username: ~
      password: ~
      authentication-database: ~

    kafka:
      producer:
        bootstrapServerHost: ~
        topic: ~
    redis:
      host: ~
      port: ~

application:
  version: @project.version@
server:
  port: 8080
  servlet:
    context-path: /api/v1
    application-display-name: votes-api
spring:
  mvc:
    throw-exception-if-no-handler-found: true
  redis:
    timeout: 0
    lettuce:
      pool:
        max-active: 50
        min-idle: 5
        max-idle: 50
        max-wait: 1
  data:
    redis:
      repositories:
        enabled: false
    mongodb:
      field-naming-strategy: org.springframework.data.mapping.model.SnakeCaseFieldNamingStrategy
      host: ${votes-api.configurations.datasource.host}
      port: ${votes-api.configurations.datasource.port}
      database: ${votes-api.configurations.datasource.database}
      username: ${votes-api.configurations.datasource.username}
      password: ${votes-api.configurations.datasource.password}
      authentication-database: ${votes-api.configurations.datasource.authentication-database}
  jackson:
    default-property-inclusion: non_null
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
